import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: '霓虹武士 2077',
    price: 129.99,
    description: '超可愛的 1/6 比例公仔，附帶發光武士刀！非常適合擺在辦公桌上。',
    category: 'Sci-Fi',
    image: 'https://picsum.photos/seed/samurai/400/400',
    stock: 15,
    rating: 4.8,
    isNew: true,
  },
  {
    id: '2',
    name: '銀河賞金獵人',
    price: 89.50,
    description: '附帶 3 個可愛的可替換頭雕和一個迷你噴射背包。',
    category: 'Sci-Fi',
    image: 'https://picsum.photos/seed/bounty/400/400',
    stock: 42,
    rating: 4.5,
  },
  {
    id: '3',
    name: '精靈女王 萊拉',
    price: 145.00,
    description: '精美的手繪樹脂雕像，身穿真絲連衣裙。',
    category: 'Fantasy',
    image: 'https://picsum.photos/seed/elf/400/400',
    stock: 8,
    rating: 4.9,
  },
  {
    id: '4',
    name: '機甲龍 X',
    price: 299.99,
    description: '巨大的友善龍龍！18 英寸高，翅膀觸感柔軟。',
    category: 'Anime',
    image: 'https://picsum.photos/seed/dragon/400/400',
    stock: 3,
    rating: 5.0,
    isNew: true,
  },
  {
    id: '5',
    name: '虛空行者',
    price: 65.00,
    description: '虛空編年史標準版公仔。可動性超高！',
    category: 'Sci-Fi',
    image: 'https://picsum.photos/seed/void/400/400',
    stock: 100,
    rating: 4.2,
  },
  {
    id: '6',
    name: '水晶法師',
    price: 110.00,
    description: '閃亮的水晶部件在紫外線下會發光。太神奇了！',
    category: 'Fantasy',
    image: 'https://picsum.photos/seed/mage/400/400',
    stock: 20,
    rating: 4.6,
  }
];